Nbs code patterns
VertaAI/examples pull request #62
Opened 2023-01-09 14:29 UTC by cfascina

## Impact and Context
Code patterns for developed NBs.

## Risks and Area of Effect

## Testing
- [ ] Unit test
- [ ] Deployed to dev env
- [x] Other (explain) 

## Reverting
- [ ] Contains Migration - _Do Not Revert_

2023-01-09 21:04 UTC, liuverta requested changes
Sorry to trouble you, Caio—I noticed that we could improve the model/endpoint names a little to make them more accurate with how we'd like users to name them.

2023-01-10 18:43 UTC, cfascina commented on deployment/huggingface/yolos-seq2seq.ipynb
> +        "ENDPOINT_NAME = 'object-detection-hugging-face'"
Done.

2023-01-10 18:46 UTC, cfascina commented on deployment/tfhub/object-detection-url.ipynb
> +        "ENDPOINT_NAME = 'object-detection-tfhub-url'"
Done.

2023-01-10 18:46 UTC, cfascina commented on deployment/tfhub/object-detection-base64.ipynb
> +        "ENDPOINT_NAME = 'object-detection-tfhub-base64'"
Done.

2023-01-10 18:49 UTC, cfascina commented on deployment/pytorch/torch-hub-yolov5.ipynb
> +        "ENDPOINT_NAME = 'object-detection-pytorch'"
Done.

2023-01-10 18:50 UTC, cfascina commented
> Sorry to trouble you, Caio—I noticed that we could improve some of the model/endpoint names a little to make them more accurate with how we'd like users to name them.

It really makes more sense with these changes :+1:

2023-01-10 18:52 UTC, liuverta approved these changes

2023-01-10 18:54 UTC, merged